apiVersion: datadoghq.com/v1beta1
kind: DatadogMonitor
metadata:
  name: apm-error-rate-example
spec:
  name: my-service error rate
  query: 'avg(last_5m):sum:trace.servlet.request.errors{env:staging,service:my-service} / sum:trace.servlet.request.hits{env:staging,service:my-service} > 0.05'
  type: query alert
  message: 'Service my-service has a high error rate on env:stg'
  tags:
    - service:my-service
    - env:staging
